//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmdCapsDBClassTools.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Testing\\TestCrudAndRefresh")]
        public string DefaultFileLocation {
            get {
                return ((string)(this["DefaultFileLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultIndividualTable {
            get {
                return ((string)(this["DefaultIndividualTable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultObjectType {
            get {
                return ((int)(this["DefaultObjectType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultReferences {
            get {
                return ((string)(this["DefaultReferences"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"'sysdiagrams','CLRDataTypeConversions', 'LUT_PrimaryTagType', 'LUT_SecondaryTagType', 'LUT_ValidTagType', 'TempErredTagsToCheck', 'TempOrderedTagsToUpdate', 'TempTagOrderQueue', 'TempTags', 'Counties', 'ValidTagTypeToReportingGroup_Rework', 'ValidTagTypeToRegistrationStatus_Rework', 'ValidTagTypeRegistrationStatus_Rework', 'ValidTagType_Rework', 'PlateMappingsInventory_Rework', 'LUT_VIMS_To_Registration_Mapping', 'ReportingGroup_Rework', 'dtCities', 'dtCounties', 'Employee', 'EmployeeProduct', 'INS_Company', 'INS_Contact', 'INS_ContactNAICLink', 'INS_NAIC', 'INS_OutOfStateNAIC', 'INS_Service', 'Product', 'StateFIPSCode', 'TagCategory'")]
        public string DefaultExcludeTables {
            get {
                return ((string)(this["DefaultExcludeTables"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DORResources")]
        public string DefaultDB {
            get {
                return ((string)(this["DefaultDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[Encrypt:Data Source=caps-sqldev1;Initial Catalog=DORResources;User ID=sa;Passwor" +
            "d=Si9r1e1n]")]
        public string DefaultConn {
            get {
                return ((string)(this["DefaultConn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DORResources")]
        public string DefaultClassNamespace {
            get {
                return ((string)(this["DefaultClassNamespace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultSeperateCRUD {
            get {
                return ((bool)(this["DefaultSeperateCRUD"]));
            }
        }
    }
}
