//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapsDBClassTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapsDBClassTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @crlf VARCHAR(10) = &apos;
        ///&apos;
        ///DECLARE @tab VARCHAR(9) = &apos;	&apos;
        ///DECLARE @filename VARCHAR(MAX)
        ///DECLARE @Class VARCHAR(MAX)
        ///DECLARE @ColList VARCHAR(MAX)
        ///DECLARE @GetList VARCHAR(MAX)
        ///DECLARE @GetParms VARCHAR(MAX)
        ///DECLARE @KeyList VARCHAR(MAX)
        ///DECLARE @TableName VARCHAR(255)
        ///DECLARE @listID INT
        ///SELECT @listID = MAX(TableID)
        ///FROM @TableInfoList
        ///
        ///WHILE @listID &gt; 0
        ///BEGIN
        ///	SELECT @TableName = TableName,
        ///		@GetParms  = CASE
        ///						WHEN key_ordinal IS NOT NULL
        ///							THEN COALESCE(
        ///								@Get [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateClassDefinitions {
            get {
                return ResourceManager.GetString("CreateClassDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @crlf VARCHAR(10) = &apos;
        ///&apos;
        ///DECLARE @tab VARCHAR(9) = &apos;	&apos;
        ///DECLARE @filename VARCHAR(MAX)
        ///DECLARE @Class VARCHAR(MAX)
        ///DECLARE @ColList VARCHAR(MAX)
        ///DECLARE @GetList VARCHAR(MAX)
        ///DECLARE @GetParms VARCHAR(MAX)
        ///DECLARE @GetParmsRouting VARCHAR(MAX)
        ///DECLARE @TableName VARCHAR(255)
        ///DECLARE @listID INT
        ///SELECT @listID = MAX(TableID)
        ///FROM @TableInfoList
        ///
        ///WHILE @listID &gt; 0
        ///BEGIN
        ///	SELECT @TableName = TableName,
        ///		@GetParms  = COALESCE(
        ///								@GetParms + &apos;, &apos;+DotNetCLRDataType+&apos; &apos;+ColumnName, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateControllerDefinitions {
            get {
                return ResourceManager.GetString("CreateControllerDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @crlf VARCHAR(10) = &apos;
        ///&apos;
        ///DECLARE @tab VARCHAR(9) = &apos;	&apos;
        ///DECLARE @TableName VARCHAR(255)
        ///DECLARE @filename VARCHAR(MAX)
        ///
        ///DECLARE @ColList VARCHAR(MAX)
        ///DECLARE @WhereList VARCHAR(MAX)
        ///DECLARE @SetList VARCHAR(MAX)
        ///DECLARE @KeyParams VARCHAR(MAX)
        ///DECLARE @AllParams VARCHAR(MAX)
        ///DECLARE @InsertParams VARCHAR(MAX)
        ///DECLARE @InsertList VARCHAR(MAX)
        ///
        ///DECLARE @deleteProcDef VARCHAR(MAX)
        ///DECLARE @getProcDef VARCHAR(MAX)
        ///DECLARE @getallProcDef VARCHAR(MAX)
        ///DECLARE @insertProcDef VARCHAR(MAX)
        ///DECLARE @updateProcD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateCrudProcedureDefinitions {
            get {
                return ResourceManager.GetString("CreateCrudProcedureDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @crlf VARCHAR(10) = &apos;
        ///&apos;
        ///DECLARE @tab VARCHAR(9) = &apos;	&apos;
        ///DECLARE @filename VARCHAR(MAX)
        ///DECLARE @Class VARCHAR(MAX)
        ///DECLARE @ColList VARCHAR(MAX)
        ///DECLARE @GetList VARCHAR(MAX)
        ///DECLARE @GetParms VARCHAR(MAX)
        ///DECLARE @TableName VARCHAR(255)
        ///DECLARE @listID INT
        ///SELECT @listID = MAX(TableID)
        ///FROM @TableInfoList
        ///
        ///WHILE @listID &gt; 0
        ///BEGIN
        ///	SELECT @TableName = TableName,
        ///		@GetParms  = CASE
        ///						WHEN key_ordinal IS NOT NULL
        ///							THEN COALESCE(
        ///								@GetParms + &apos;, &apos;+DotNetCLRDataType+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateModelClassDefinitions {
            get {
                return ResourceManager.GetString("CreateModelClassDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @crlf VARCHAR(10) = &apos;
        ///&apos;
        ///DECLARE @tab VARCHAR(9) = &apos;	&apos;
        ///DECLARE @filename VARCHAR(MAX)
        ///DECLARE @Class VARCHAR(MAX)
        ///DECLARE @ColList VARCHAR(MAX)
        ///DECLARE @GetList VARCHAR(MAX)
        ///DECLARE @GetParms VARCHAR(MAX)
        ///DECLARE @TableName VARCHAR(255)
        ///DECLARE @listID INT
        ///SELECT @listID = MAX(TableID)
        ///FROM @TableInfoList
        ///
        ///WHILE @listID &gt; 0
        ///BEGIN
        ///	SELECT @TableName = TableName,
        ///		@GetParms  = CASE
        ///						WHEN key_ordinal IS NOT NULL
        ///							THEN COALESCE(
        ///								@GetParms + &apos;, &apos;+DotNetCLRDataType+ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateModelCrud {
            get {
                return ResourceManager.GetString("CreateModelCrud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @crlf VARCHAR(10) = &apos;
        ///&apos;
        ///DECLARE @tab VARCHAR(9) = &apos;	&apos;
        ///DECLARE @filename VARCHAR(MAX)
        ///DECLARE @WcfClass VARCHAR(MAX)
        ///DECLARE @IWcfClass VARCHAR(MAX)
        ///DECLARE @Methods VARCHAR(MAX) = &apos;&apos;
        ///DECLARE @IMethods VARCHAR(MAX) = &apos;&apos;
        ///DECLARE @TableName VARCHAR(255)
        ///DECLARE @GetList VARCHAR(MAX)
        ///DECLARE @GetParms VARCHAR(MAX)
        ///DECLARE @listID INT
        ///SELECT @listID = MAX(TableID)
        ///FROM @TableInfoList
        ///
        ///WHILE @listID &gt; 0
        ///BEGIN
        ///	SELECT @TableName = TableName
        ///	FROM @TableInfoList
        ///	WHERE TableID = @listID [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateWCFClassDefinitions {
            get {
                return ResourceManager.GetString("CreateWCFClassDefinitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Newtonsoft.Json;
        ///using System;
        ///using System.Net;
        ///using System.Net.Http;
        ///using System.Net.Http.Headers;
        ///using System.Text;
        ///
        ///namespace CapsDBClassTools
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Interface to PROS REST service repository
        ///    /// &lt;/summary&gt;
        ///    public interface IRestfulRepository
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Template method for retrieving data from a REST service
        ///        /// &lt;/summary&gt;
        ///        /// &lt;typeparam name=&quot;T&quot;&gt;Data transmission object&lt;/typeparam&gt;
        ///        /// &lt;param na [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RestfulRepository {
            get {
                return ResourceManager.GetString("RestfulRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///DECLARE @NameSpace VARCHAR(255) = &apos;Pros.Model&apos;,--My Default
        ///	@IndividualTable VARCHAR(255) = NULL, -- Leave Null For all Tables
        ///	@References VARCHAR(255) = NULL,
        ///	@Database VARCHAR(50) = NULL,
        ///	@ExcludeTables VARCHAR(2018) = null
        ///*/
        ///SET NOCOUNT ON
        ///
        ///SELECT @IndividualTable = CASE @IndividualTable WHEN &apos;&apos; THEN NULL ELSE @IndividualTable END, -- Leave Null For all Tables
        ///	@References = CASE @References WHEN &apos;&apos; THEN NULL ELSE @References END
        ///
        ///DECLARE @tableinfo VARCHAR(MAX) = &apos;
        ///	SELECT 
        ///		T.Tab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableInfo {
            get {
                return ResourceManager.GetString("TableInfo", resourceCulture);
            }
        }
    }
}
